
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author altheacruz
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficult = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        easy = new javax.swing.JButton();
        help = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        difficult.setBackground(new java.awt.Color(204, 0, 102));
        difficult.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        difficult.setForeground(new java.awt.Color(255, 204, 204));
        difficult.setText("DIFFICULT");
        difficult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultActionPerformed(evt);
            }
        });
        getContentPane().add(difficult, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 110, 40));

        medium.setBackground(new java.awt.Color(255, 153, 0));
        medium.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        medium.setForeground(new java.awt.Color(128, 59, 9));
        medium.setText("MEDIUM");
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });
        getContentPane().add(medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 90, 40));

        easy.setBackground(new java.awt.Color(0, 255, 153));
        easy.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        easy.setForeground(new java.awt.Color(0, 51, 51));
        easy.setText("EASY");
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });
        getContentPane().add(easy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 80, 40));

        help.setBackground(new java.awt.Color(0, 248, 203));
        help.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        help.setForeground(new java.awt.Color(102, 102, 102));
        help.setText("HELP");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 90, 40));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startBG.png"))); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed
        // TODO add your handling code here:
        MainGame easy = new MainGame();
        easy.show();
        easy.difficultySelect("average");
        dispose();
    }//GEN-LAST:event_easyActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        InstPage help = new InstPage();
        help.show();
    }//GEN-LAST:event_helpActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        // TODO add your handling code here:
        MainGame average = new MainGame();
        average.show();
        average.difficultySelect("average");
        dispose();        
    }//GEN-LAST:event_mediumActionPerformed

    private void difficultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultActionPerformed
        // TODO add your handling code here:
        MainGame hard = new MainGame();
        hard.show();
        hard.difficultySelect("difficult");
        dispose();
    }//GEN-LAST:event_difficultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
        UIManager.setLookAndFeel( new FlatDarkLaf() );
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
        } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton difficult;
    private javax.swing.JButton easy;
    private javax.swing.JButton help;
    private javax.swing.JLabel image;
    private javax.swing.JButton medium;
    // End of variables declaration//GEN-END:variables
}
